Stratio/stratio-metabase

testsAT/pom.xml
Change BDT version to 0.7.0-SNAPSHOT
=> [QATM-969] Change bdt version in pom.xml

testPF/README.md
=> [AT][Performance] Fix some missings variable references in README

testPF/README.md, testPF/pom.xml
=> [testsPF] Fix pom for performance tests

CHANGELOG.md
=> Release0.1.0

project.clj
=> [DGPB-1154] Problemas en la verificación del hostname de postgrestls

Jenkinsfile, resources/kms/psql-connection.sh
=> change jdbc_parameters name

testsAT/README.md, testsAT/pom.xml, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_nightly_IT.java, testsAT/src/test/resources/features/installation/001_disc_installPostgres.feature, testsAT/src/test/resources/features/installation/002_disc_installDiscovery.feature
=> Changes to include snapshot version in installation

CHANGELOG.md, src/metabase/api/session.clj, src/metabase/models/user.clj, src/metabase/public_settings.clj
=> [DGPB-1171] -  Add armadillo admin auto-create user

testsAT/src/test/java/com/stratio/schema/discovery/specs/Common.java, testsAT/src/test/java/com/stratio/schema/discovery/specs/GivenSpec.java, testsAT/src/test/java/com/stratio/schema/discovery/specs/ThenSpec.java, testsAT/src/test/java/com/stratio/schema/discovery/specs/WhenSpec.java
[QATM-1431] Delete sql methods from specs
=> [QATM-1431] Delete sql methods from specs

Jenkinsfile
-  [ ] Run the frontend and integration tests with  `yarn && yarn run prettier && yarn run lint && yarn run flow && ./bin/build version uberjar && yarn run test`)
=> Increase build timeout

Dockerfile, bin/install_dependencies.sh, project.clj
=> Upgrade Crossdata driver

Jenkinsfile, testsAT/README.md, testsAT/src/test/resources/features/001_installation/000_disc_createPolicies.feature, testsAT/src/test/resources/features/001_installation/001_disc_installPostgres.feature, testsAT/src/test/resources/features/001_installation/002_disc_installDiscovery.feature, testsAT/src/test/resources/features/099_uninstall/001_disc_uninstallDiscovery.feature, testsAT/src/test/resources/features/099_uninstall/002_disc_deletePolicies.feature, testsAT/src/test/resources/features/099_uninstall/003_disc_uninstallPostgres.feature
Include version 0.31.0-SNAPSHOT and change param name REGISTERSERVICEOLD to DISCOVERY_POLICIES
=> Add last snapshot

CHANGELOG.md, Dockerfile, bin/install_dependencies.sh, project.clj
=> downgrade crossdata

testPF/src/test/scala/com/stratio/performance/tests/Perf10Users30MinutesHighActivityCrossdata.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf10Users30MinutesHighActivityPostgreSQL.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf10Users30MinutesLowActivityCrossdata.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf10Users30MinutesLowActivityPostgreSQL.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf150Users30MinutesHighActivityCrossdata.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf150Users30MinutesHighActivityPostgreSQL.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf150Users30MinutesLowActivityCrossdata.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf150Users30MinutesLowActivityPostgreSQL.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf200UsersMax5Minutes10UsersIncrementHighActivityCrossdata.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf200UsersMax5Minutes10UsersIncrementHighActivityPostgreSQL.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf200UsersMax5Minutes10UsersIncrementLowActivityCrossdata.scala, testPF/src/test/scala/com/stratio/performance/tests/Perf200UsersMax5Minutes10UsersIncrementLowActivityPostgreSQL.scala, testPF/src/test/scala/com/stratio/performance/tests/Stab10Users24HoursLowActivityPostgreSQL.scala, testPF/src/test/scala/com/stratio/performance/tests/Stab10Users48HoursLowActivityPostgreSQL.scala
=> [PF] Fix performance tests duration

testsAT/README.md, testsAT/src/test/resources/features/001_installation/000_disc_createPolicies.feature, testsAT/src/test/resources/features/001_installation/001_disc_installPostgres.feature, testsAT/src/test/resources/features/001_installation/002_disc_installDiscovery.feature, testsAT/src/test/resources/features/001_installation/003_disc_setupDiscovery.feature, testsAT/src/test/resources/features/002_connections/001_disc_connectionPG.feature, testsAT/src/test/resources/features/002_connections/002_disc_connectionXD.feature, testsAT/src/test/resources/features/003_login/003_disc_updateEnvDiscovery.feature, testsAT/src/test/resources/features/099_uninstall/001_disc_uninstallDiscovery.feature, testsAT/src/test/resources/features/099_uninstall/002_disc_deletePolicies.feature, testsAT/src/test/resources/features/099_uninstall/003_disc_uninstallPostgres.feature, testsAT/src/test/resources/schemas/objectPolicy.conf
- Changes to obtain vault token and add/delete gosec policies
- Update version
=> Changes to obtain vault token and add/delete gosec policies

resources/kms/b-log.sh, resources/kms/kms_utils.sh, resources/kms/psql-connection.sh, resources/kms/secrets.sh, resources/kms/tls-config.sh, resources/kms/truststore-config.sh
=> Update KMS utils 4.1

testsAT/pom.xml, testsAT/src/test/java/com/stratio/schema/discovery/connections/DISC_connectionPG_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/connections/DISC_connectionXD_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_createPolicy_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_deletePolicy_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_install_discovery_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_install_postgres_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_nightly_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_setup_discovery_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_uninstall_discovery_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_uninstall_postgres_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/login/DISC_login_IT.java
=> [QATM-1678] cucumber-reporting tool added

CHANGELOG.md
=> changelog refactor

Dockerfile, bin/start, resources/kms/secrets.sh, resources/log4j2.xml
=> [DGPB-1702] Metabase logs are losing in discovery logs

Dockerfile, bin/start, resources/kms/secrets.sh, resources/log4j2.xml
=> Cherry pick logs

testsAT/README.md, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_install_discovery_CC_IT.java, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_uninstall_discovery_CC_IT.java, testsAT/src/test/resources/features/001_installation/004_disc_installDiscoveryCC.feature, testsAT/src/test/resources/features/099_uninstall/004_disc_uninstallDiscoveryCC.feature
Conseguida bola azul al ejecutarlo con Jenkins
=> QATM-1866 Install/Uninstall Discovery CCT

testsAT/src/test/resources/features/002_connections/001_disc_connectionXD_CCT.feature, testsAT/src/test/resources/features/002_connections/002_disc_connectionPG_CCT.feature
=> [AT][QATM-1967] Add retries when sending rest requests to discovery

testsAT/README.md, testsAT/src/test/resources/features/002_connections/001_disc_connectionXD_CCT.feature, testsAT/src/test/resources/features/002_connections/002_disc_connectionPG_CCT.feature
=> adapt to new step for session id retrieval

testsAT/pom.xml
=> [QATM-1984] update testsAT pom to latest stable bdt

testsAT/src/test/resources/features/002_connections/001_disc_connectionXD_CCT.feature
=> [QATM-2065] fix check to obtain crossdata server

testsAT/README.md, testsAT/src/test/resources/features/001_installation/002_disc_installDiscoveryCC.feature
Fix al error en la instalación debido a la actualización del descriptor (https://github.com/Stratio/saas-universe/pull/648) 
Además, se eliminan referencias a DISC_ADVANCED_INSTALL pues el parámetro ya no aplica
=> [AT][QATM-2175] Fix installation error in nightly

bin/install_dependencies.sh, bin/start, local-query-execution-factory/pom.xml, src/metabase/driver/crossdata2.clj, src/metabase/driver/generic_sql.clj
=> [ROCK-30] Impersonation

CHANGELOG.md, Dockerfile, bin/install_dependencies.sh, project.clj
=> Upgrade Crossdata library

src/metabase/db/spec.clj
=> Force prepareThreshold=0

CHANGELOG.md, Dockerfile, project.clj
=> upgrading xd jdbc driver to 2.14.4

CHANGELOG.md, Dockerfile, project.clj
* upgrading xd jdbc driver to 2.14.4
* relaunch pr
=> upgrading xd jdbc driver to 2.14.4 (#111)

src/metabase/db/spec.clj
=> Update spec.clj (#109)

CHANGELOG.md, src/metabase/driver/crossdata2.clj
=> changed Crossdata2 driver to fix problem with personalize queries

src/metabase/driver/crossdata2.clj
=> fixing crossdata2 driver with impersonation flag

frontend/src/metabase/admin/databases/components/DeleteDatabaseModal.jsx
* Update spec.clj (#109)
* allow delete database with localized DELETE
=> Fix/delete word database (#123)

CHANGELOG.md, src/metabase/driver/crossdata2.clj
=> fixing the error with decimal types with Crossdata

CHANGELOG.md, src/metabase/driver/crossdata2.clj
* fixing the error with decimal types with Crossdata
* relaunch pr
=> fixing the error with decimal types with Crossdata (#139)

Jenkinsfile
=> increasing dev timeout in Jenkins

src/metabase/driver/crossdata2.clj
=> refactoring crossdata2 driver to remove unused code lines

src/metabase/driver/generic_sql/query_processor.clj, test/metabase/query_processor_test/remapping_test.clj, test/metabase/test/data/dataset_definitions.clj
=> fix for error with fk to same table

bin/start
=> Max heap as docker memory percentage configurable in descriptor

bin/start
=> Max heap jvm

resources/kms/psql-connection.sh, resources/kms/secrets.sh, resources/kms/tls-config.sh
=> fixing the compatibility in updating Datio instances

CHANGELOG.md
=> Changing Changelog with fix [ROCK-459] about Datio compatibility

CHANGELOG.md
=> modifying Changelog 0.35

CHANGELOG.md, src/metabase/db.clj, src/metabase/db/spec.clj, src/metabase/driver/generic_sql.clj
=> avoiding Discovery checks Crossdata connection each 3 mins

CHANGELOG.md, project.clj, resources/log4j2.xml, resources/log4j2_backup.xml
=> Logs standard format

bin/change-version.sh
=> adding change-version.sh file

resources/log4j2.xml
=> fixing to allow showing the logs per each Metabase module

CHANGELOG.md, src/metabase/api/session.clj, src/metabase/config.clj, src/metabase/stratio/header_user_info.clj
=> [ROCK-629] Add jwt authentication - branch 0.34

CHANGELOG.md, resources/frontend_client/inline_js/auto_header_login.js, src/metabase/api/session.clj, src/metabase/util.clj, test/metabase/public_settings_test.clj
=> Fix too strict site-url validation and autologin

modules/drivers/crossdata/src/metabase/driver/crossdata.clj, resources/migrations/000_migrations.yaml, resources/migrations/stratio_migrations.yaml
=> Updating crossdata2driver to crossdata

src/metabase/api/session.clj
=> [ROCK-1218] Fix: error when login with wrong user or password

CHANGELOG.md, frontend/src/metabase/components/FieldValuesWidget.jsx, frontend/src/metabase/entities/fields.js, frontend/src/metabase/lib/redux.js, frontend/src/metabase/parameters/components/ParameterValueWidget.jsx, frontend/src/metabase/parameters/components/ParameterWidget.jsx, frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget.jsx, frontend/src/metabase/redux/metadata.js, frontend/src/metabase/services.js, src/metabase/api/field.clj, test/metabase/api/field_test.clj
* funciona con filtros de misma tabla
* Funciona el endpoint que obtiene los values de un field con values de otro field relacionado. Tiene comentarios.
* Terminado el desarrollo back de los filtros anidados a falta de pruebas unitarias
* Pruebas unitarias para los filtros anidados
* Added dates in the nested filters
* changing some funcion and variables names
* changed load values filter endpoint
* generate new query
* fixing some errors about nested filters
* Changelog
* Adding comments in javascript files to identify Stratio changes
Co-authored-by: mhidalgo-stratio <mhidalgo@stratio.com>
-  [ ] Run the …
=> Filtros anidados (#153)

CHANGELOG.md, Jenkinsfile, src/metabase/api/session.clj
=> [ROCK-1218] Fix: error when login with wrong user or password - branch 0.34

Jenkinsfile
=> Double release timeout in Jenkinsfile

CHANGELOG.md, src/metabase/api/session.clj, src/metabase/events/activity_feed.clj, src/metabase/stratio/audit_log.clj
=> [ROCK-1220] Audit logs

bin/install_dependencies.sh
=> Fix install xd artifact local 0.34

resources/migrations/000_migrations.yaml
=> [ROCK-1300] Fix unselected SSL option in crossdata database config after migration

src/metabase/middleware/session.clj, test/metabase/middleware/session_test.clj
=> Do not set SameSite atribute in session header

CHANGELOG.md, Dockerfile, bin/install_dependencies.sh, modules/drivers/crossdata/project.clj, pom.xml, project.clj
=> set xd jdbc driver 2.17.0 release version

frontend/src/metabase/components/FieldValuesWidget.jsx, frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
=> [Rock-1447] Fix params question

CHANGELOG.md
-  [x] If there are changes to the backend codebase, run the backend tests with `lein test && lein eastwood && lein bikeshed && lein docstring-checker && ./bin/reflection-linter`
-  [x] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeOrkbmNaq9pOJ_E/viewform)
=> Update changelog for 0.35.1

Dockerfile, frontend/src/metabase/components/FieldValuesWidget.jsx, frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
* fix parameters on question
* removed traces
=> [Rock-1447] Cherry-pick Fix params question 0.36 (#193)

Dockerfile, bin/install_dependencies.sh, modules/drivers/crossdata/project.clj, pom.xml, project.clj
=> set xd jdbc driver version to 2.17.0

bin/start
=> [ROCK-1496] [ROCK-1696] Changes in entrypoint in order to accept a complete postgres URL

bin/start
=> [ROCK-1496] [ROCK-1696] [Cherrypick] Changes in entrypoint in order to accept a complete postgres URL 

modules/drivers/crossdata/src/metabase/driver/crossdata.clj
=> [ROCK-1789] Crossdata driver - Replace 'default' alias with 'defaultalias'

CHANGELOG.md
=> Add 0.37 changelog

src/metabase/api/session.clj
=> Fix/do not add @ to user name if it contains it

src/metabase/api/session.clj
=> Check @ in user name when creating user-email (#205)

Dockerfile
=> [ROCK-1926] Discovery cicd uberjar in docker

CHANGELOG.md, Dockerfile
=> Cherry pick ROCK-1926

Dockerfile, discovery-cicd-integration/discovery-cicd-service/run, oauth-proxy-integration/nginx-confs/nginx.conf.native-auth, oauth-proxy-integration/nginx-confs/nginx.conf.sso-auth
=> [ROCK-1963] Discovery CI/CD API

Dockerfile
=> Add superuser check

CHANGELOG.md
=> Add changelog for 038

modules/drivers/crossdata/src/metabase/driver/crossdata.clj
https://stratio.atlassian.net/browse/ROCK-2259
=> [ROCK-2259] change println for log/debug in crossdata driver

modules/drivers/crossdata/resources/metabase-plugin.yaml, modules/drivers/crossdata/src/metabase/driver/crossdata.clj
https://stratio.atlassian.net/browse/ROCK-2259
=> [ROCK-2259] Feature/log4j format branch-0.38

modules/drivers/crossdata/resources/metabase-plugin.yaml
=> add default xd port 8000

CHANGELOG.md, Dockerfile
=> Bump discovery-cicd version to 1.2.0-e81eb29

CHANGELOG.md, modules/drivers/crossdata/src/metabase/driver/crossdata.clj
=> Improve fault tolerance on Crossdata driver describe-table

CHANGELOG.md, Dockerfile
=> Bump discovery-cicd version to 1.2.0-e81eb29 (#214)

CHANGELOG.md, modules/drivers/crossdata/src/metabase/driver/crossdata.clj
=> Improve fault tolerance on Crossdata driver describe-table (#220)

CHANGELOG.md, Dockerfile
=> Bump export/import artifact to version 1.2.1-1570d16

modules/drivers/crossdata/resources/metabase-plugin.yaml, project.clj
=> Fix: do not declare stratio.jdbc as dependency in XD plugin manifest

CHANGELOG.md, modules/drivers/stratiopostgres/project.clj, modules/drivers/stratiopostgres/resources/metabase-plugin.yaml, modules/drivers/stratiopostgres/src/metabase/driver/stratiopostgres.clj, src/metabase/api/session.clj
=> [ROCK-2785] Add custom postgres driver that sets variable with logged user

Dockerfile
=> Fix docker image in Dockerfile

testsAT/pom.xml, testsAT/src/test/java/com/stratio/schema/discovery/installation/DISC_nightlyCCT_Compatible_IT.java, testsAT/src/test/resources/features/001_installation/002_disc_installDiscoveryCC_Compatible.feature, testsAT/src/test/resources/features/002_connections/001_disc_connectionXD_CCT_Compatible.feature, testsAT/src/test/resources/features/002_connections/002_disc_connectionPG_CCT.feature, testsAT/src/test/resources/features/002_connections/002_disc_connectionPG_CCT_Compatible.feature, testsAT/src/test/resources/features/003_login/003_disc_updateEnvDiscovery.feature, testsAT/src/test/resources/features/099_uninstall/001_disc_uninstallDiscovery.feature, testsAT/src/test/resources/features/099_uninstall/001_disc_uninstallDiscoveryCC_Compatible.feature, testsAT/src/test/resources/features/099_uninstall/002_disc_deletePolicies.feature, testsAT/src/test/resources/features/templates/Discovery_Templates.feature, testsAT/src/test/resources/features/templates/Discovery_Templates_Compatible.feature, testsAT/src/test/resources/schemas/crossdata_policy_compatible.json
Update TestAT for execution with enviroments with Universe 0.4
=> [ROCK-3095] TestAT Discovery - universe-04

CHANGELOG.md, Dockerfile
=> [ROCK-3341] Cherry-pick (branch-1.9) Bump export/import artifact to version 1.2.1-1570d16

CHANGELOG.md, bin/install_dependencies.sh, modules/drivers/crossdata/project.clj, pom.xml, project.clj
=> [ROCK-3350] Upgrade Crossdata JDBC to 2.19.0

CHANGELOG.md, Dockerfile
=> Fix vulnerabilities(branch-0.39)

CHANGELOG.md, Dockerfile, Jenkinsfile
=> Cherrypick: Fix vulnerabilities and CHANGELOG (#239)

JenkinsfileAnchore, modules/drivers/crossdata/project.clj, project.clj
=> Add Jenkinsfile with anchore

Dockerfile, discovery-cicd-integration/discovery-cicd-service/run
=> add new discovery cicd prerelease and a Options variable

CHANGELOG.md
=> add changelog for 0.39.2 version

Dockerfile
=> [ROCKET-NA] Remove vulnerabilities ubuntu

CHANGELOG.md, oauth-proxy-integration/nginx-confs/nginx.conf.native-auth, oauth-proxy-integration/nginx-confs/nginx.conf.sso-auth
=> [ROCK-3900] Make nginx timeout for discovery-cicd configurable

CHANGELOG.md, k8s/keos/README.md, k8s/keos/discovery-config.yaml, k8s/keos/discovery-deployment.yaml, k8s/keos/discovery-ingress.yaml, k8s/keos/discovery-service.yaml, k8s/keos/temporal/postgres-deployment.yaml, k8s/keos/temporal/postgres-service.yaml, k8s/keos/temporal/postgres-storage.yaml, k8s/minikube/README.md, k8s/minikube/discovery-config.yaml, k8s/minikube/discovery-deployment.yaml, k8s/minikube/discovery-ingress.yaml, k8s/minikube/discovery-service.yaml, k8s/minikube/external/postgres-endpoint.yaml, k8s/minikube/external/postgres-service.yaml, k8s/ns-discovery.json, oauth-proxy-integration/docker-entrypoint.sh, oauth-proxy-integration/nginx-confs/nginx.conf.native-auth-without-ssl, oauth-proxy-integration/rc.local, pom.xml, resources/kms/secrets.sh, resources/locales.clj
=> [ROCK-3762] Discovery Deploy k8s

k8s/keos/discovery-deployment.yaml, k8s/minikube/discovery-deployment.yaml
=> [ROCK-3772 ] Fix image deploy k8s

CHANGELOG.md, oauth-proxy-integration/docker-entrypoint.sh, oauth-proxy-integration/nginx-confs/nginx.conf.log-access-data, oauth-proxy-integration/nginx-confs/nginx.conf.native-auth, oauth-proxy-integration/nginx-confs/nginx.conf.sso-auth
=> [ROCK-3933] Open public endpoints in SSO proxy and log data access

src/metabase/driver/postgres.clj
=> Do not change ssl options in postgres connection string

frontend/src/metabase/auth/auth.js, src/metabase/core.clj, src/metabase/server/handler.clj, src/metabase/stratio/auth.clj, src/metabase/stratio/config.clj, src/metabase/stratio/header_user_info.clj, src/metabase/stratio/util.clj
=> [ROCK-4172] SSO integration: auto-login via headers

src/metabase/driver/sql_jdbc/execute.clj
=> handle empy resultSetMetadata

project.clj, src/metabase/task.clj, stratio/Dockerfile
=> [ROCK-4176] Remove vulnerabilities

src/metabase/stratio/auth.clj
=> [ROCK-4174] Set response header with username

CHANGELOG.md, oauth-proxy-integration/nginx-confs/nginx.conf.log-access-data, resources/kms/encrypt-passwords.sh, resources/kms/secrets.sh
=> [ROCK-4293] Encrypt data audit

oauth-proxy-integration/nginx-confs/nginx.conf.log-access-data, oauth-proxy-integration/nginx-confs/nginx.conf.sso-auth
=> Fix: user placeholder in health log

CHANGELOG.md, oauth-proxy-integration/nginx-confs/nginx.conf.log-access-data, oauth-proxy-integration/nginx-confs/nginx.conf.sso-auth, resources/kms/encrypt-passwords.sh, resources/kms/secrets.sh
* Download passwords to encrypt data audit
* Make response_message on nginx config
* Otro enfoque
* Enfoque inicial
This reverts commit a8674f3f2b6d4681a6dd7638f469a0921ae96cc4.
* Enable encrypt password
* Add encrypt and base64 encode algorithms
* Excel management via isBinary var
* Encryption error management
* Include new format encrypted message
Changelog
* Fix info trace
* Encrypted data to json
-  [ ] Sign the [Contributor License Agreement](https://docs.google.com/a/metabase.com/forms/d/1oV38o7b9ONFSwuzwmERRMi9SYrhYeO …
=> [ROCK-4293] Encrypt data audit (#264)

CHANGELOG.md
=> Changelog entry for 0.38.1-0.1.0 branch

CHANGELOG.md
=> Leave 0.38.1-0.1.0 with Pending changelog

VERSION_HISTORY.md
=> Add fake entry to version_history.md

Jenkinsfile
=> Deactivate anchore

Jenkinsfile
=> Add upstream version to Jenkinsfile

CHANGELOG.md, src/metabase/stratio/auth.clj
=> Fix: lowercase email and delete invalid sessions in autologin

CHANGELOG.md, src/metabase/stratio/auth.clj, src/metabase/stratio/middleware.clj
=> [ROCK-4767] Fix: Allow emails as values of user header in auto-login

CHANGELOG.md, src/metabase/server/handler.clj, src/metabase/stratio/middleware.clj
=> [ROCK-4767] Fix: Automatic auto-login with expired sessions

CHANGELOG.md, src/metabase/stratio/middleware.clj
=> [ROCK-NA] Fix: do not try to auto login in public api endpoints

CHANGELOG.md, project.clj
=> [ROCK-NA] Fix: remove vulnerabilities (commons-compress)

Jenkinsfile
=> Update for Jenkins @ k8s (#282)

CHANGELOG.md, project.clj
=> [ROCK-5578] Fix new vulnerabilities

project.clj
=> Fix: log4j2 vulnerability

CHANGELOG.md, resources/locales.clj, src/metabase/stratio/middleware.clj
=> [ROCK-6310] Forbid first_name editing but allow superusers to edit user details

CHANGELOG.md, src/metabase/stratio/middleware.clj
* Allow superuser editing
* Test with log
* Test 2
* Remove is admin
* Working ugly
* Clean version
* Code review
* CHangelog
=> [ROCK-6310] Forbid first_name editing but allow superusers to edit user details (#287)

deps.edn, stratio/Dockerfile
=> Comment unused Java source folder

bin/build-drivers/deps.edn, bin/lint-migrations-file/deps.edn, bin/release/deps.edn, deps.edn, stratio/Dockerfile
=> Solve Conflicting data-reader mapping while building drivers

src/metabase/stratio/auth.clj
=> Remove deprecated sync-admin-group? from create-and-sync-groups! in stratio/auth.clj

CHANGELOG.md, src/metabase/core.clj
=> Do not load sample database on start up
